version: "3"

networks:
  rustdesk-net:
    driver: bridge

services:
  hbbs:
    container_name: hbbs
    image: rustdesk/rustdesk-server:latest
    environment:
      - ALWAYS_USE_RELAY=N
      - RELAY_SERVER_ADDR=hbbr
      - MAX_CONNECTIONS=1000
      - CONNECTION_TIMEOUT=30
      - KEEPALIVE_INTERVAL=10
    command: hbbs
    volumes:
      - ./data/hbbs:/root
    network_mode: "host"
    restart: unless-stopped
    cpus: 4
    mem_limit: 4096m

  hbbr:
    container_name: hbbr
    image: rustdesk/rustdesk-server:latest
    environment:
      - MAX_CONNECTIONS=1000
      - CONNECTION_TIMEOUT=30
      - KEEPALIVE_INTERVAL=10
    command: hbbr
    volumes:
      - ./data/hbbr:/root
    network_mode: "host"
    restart: unless-stopped
    cpus: 4
    mem_limit: 4096m
